// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvwurkxdqjerskwpebbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12d3Vya3hkcWplcnNrd3BlYmJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwMTc0MjcsImV4cCI6MjA5OTU5MzQyN30.0sma47l2H5r4uzR9ClWi6a99yTamnlnb002ua7uC5tk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});